### ISSUE TITLE
Turning it off

### ISSUE THREAD

**Issue by stashymane** [valleyman86/EasyDMGReportGO#3]
Once I'm done with it, how do I turn off the script apart from using task manager to terminate it? Doesn't seem to be any code hinting towards turning the script off.
Also, a dialog box notifying me of the script starting would be nice.

**Comment by valleyman86** [comment]
just delete it or right click it in the tray.

On Sat, Sep 26, 2015 at 1:54 PM, Albertas Šarutis notifications@github.com
wrote:

> Once I'm done with it, how do I turn off the script apart from using task
> manager to terminate it? Doesn't seem to be any code hinting towards
> turning the script off.
> Also, a dialog box notifying me of the script starting would be nice.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/valleyman86/EasyDMGReportGO/issues/3.

## 

_Joey Gentry_
_MurderDev http://www.MurderDev.com - Developing Killer Software_
