### ISSUE TITLE
is it working now with current cs go?

### ISSUE THREAD

**Issue by dedeoglumrt** [valleyman86/EasyDMGReportGO#7]
someone says it doesnt work anyomre on steam community pls answer. regards

**Comment by valleyman86** [comment]
I wouldn't be surprised. Its 8 years old. The code is here so someone can try and make it work but I no longer play this game nor know anything about the current release state.

**Comment by dedeoglumrt** [comment]
i need this can you help me?
we can share it on steam community them so mamy people can use it. regards
